export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_REQUEST_SUCCESS = 'GET_CONTACTS_REQUEST_SUCCESS';
export const GET_CONTACTS_REQUEST_ERROR = 'GET_CONTACTS_REQUEST_ERROR';
export const TOGGLE_ISFAVORITE = 'TOGGLE_ISFAVORITE';
export const RECOVER_CONTACT = 'RECOVER_CONTACT';

export const SELECT_CONTACT = 'SELECT_CONTACT';

export const FILTER_CHANGE = 'FILTER CHANGE';
export const RAISE_ERROR = 'RAISE_ERROR';